language: java
sudo: required
jobs:
  include:
    - stage: review
      script:
        - echo 'Running tests...'
        - ./gradlew clean build
    - stage: deploy
      script:
        - bash deploy-scripts/deploy.sh
stages:
  - name: review
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
